highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://jakinbohun.github.io/resume
author: Jeremiah Akinbohun

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Jeremiah Akinbohun's Resume
name: Jeremiah Akinbohun
email: jakinbohun@gmail.com
email_full: mailto:jeremiahakinbohun@gmail.com
website: github.io/jakinbohun
website_full: https://jakinbohun.github.io/sustain
github: jakinbohun
twitter: j_akinbohun
tel: 703 408-5898
tel_full: tel:7034085898
google_maps: 'https://www.google.com/maps/place/15025+Spriggs+Valley+Ct,+Woodbridge,+VA+22193/@38.626591,-77.3782086,17z/data=!3m1!4b1!4m5!3m4!1s0x89b6f802e5251039:0xfad76f31125628e4!8m2!3d38.6265868!4d-77.3760199'
address: 15025 Spriggs Valley Court
postcode: 22193
city: Woodbridge,Virginia
country: United States
google_analytics: UA-98714738-1

# needed for travis-ci build
exclude: [vendor]
